// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxaohlkkmqcmelinqgmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4YW9obGtrbXFjbWVsaW5xZ212Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Njc3MzEsImV4cCI6MjA2MTI0MzczMX0.p9SD3R0ZrwS8z9kpzvgtx95QA7idhTyiq-CyBvzZW0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);